### ISSUE TITLE
Improve run instructions

### ISSUE THREAD

**Issue by orange451** [1arrcy1/H1z1-server-install-script#1]
A lot of people that will inevitably find this will not have git experience, and think the commands listed on the "run instructions" section will run these instructions EVERY time.

Perhaps split in to two sections for "setup" and "run"? Where run would be only the ./script command?

Or am I totally off-base in my misunderstanding?

**Comment by 1arrcy1** [comment]
I made some changes to the readme hopefully this would clear up some confusion. If it’s still unclear be sure to let me know and i will try to make it more easy ;)
